# Generated by Django 5.1.4 on 2025-01-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Shope',
        ),
    ]
