# Generated by Django 5.1.4 on 2025-02-09 09:32

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('youtube_url', embed_video.fields.EmbedVideoField(null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Price_and_weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('weight', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('sell_minimum_quantity', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.item')),
            ],
        ),
    ]
