# Generated by Django 5.1.4 on 2025-01-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_rename_iteme_price_and_weight_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_and_weight',
            name='prise',
        ),
        migrations.AddField(
            model_name='price_and_weight',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
