# Generated by Django 5.1.4 on 2025-01-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_remove_price_and_weight_prise_price_and_weight_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.category')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.item')),
            ],
        ),
    ]
