# Generated by Django 5.1.4 on 2025-01-13 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_date_customer_district_customer_house_no_and_more'),
        ('owner', '0006_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.item')),
                ('price_and_weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.price_and_weight')),
            ],
        ),
    ]
