# Generated by Django 5.1.4 on 2025-01-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Customer',
            new_name='customer',
        ),
    ]
