# Generated by Django 5.1.4 on 2025-02-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cart_customer_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
