# Generated by Django 5.1.4 on 2025-01-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_date_customer_district_customer_house_no_and_more'),
        ('order', '0002_rename_customer_cart_customer'),
        ('owner', '0006_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=1)),
                ('courier_charges', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('item', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('total_amount', models.FloatField(default=0, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
    ]
