# Generated by Django 5.1.4 on 2025-01-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_detail_ordermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
