# Generated by Django 5.1.4 on 2025-01-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_detail_unit_order_detail_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='total_price',
        ),
    ]
