# Generated by Django 5.1.4 on 2025-01-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordermaster_accepted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='courier_charges',
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='courier_charges',
            field=models.FloatField(default=0),
        ),
    ]
