# Generated by Django 5.1.4 on 2025-01-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_detail_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='total_price',
        ),
    ]
