# Generated by Django 5.1.4 on 2025-02-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_detail_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='courier_charges',
        ),
    ]
